CREATE TABLE `mobileapi_api` (
  `artifact_Id` varchar(100) NOT NULL,
  `api_id` varchar(255) NOT NULL,
  `invoke_interface` varchar(255) NOT NULL,
  `invoke_method` varchar(255) NOT NULL,
  `is_public` int(11) NOT NULL,
  `status` varchar(50) DEFAULT NULL,
  `time_created` datetime DEFAULT NULL,
  `time_modified` datetime DEFAULT NULL,
  `ver` varchar(128) NOT NULL,
  `api_name` varchar(128) NOT NULL,
  `api_type` int(11) NOT NULL,
  `api_security_level` int(10) NOT NULL,
  `api_group` varchar(128) NOT NULL,
  `full_method` varchar(500) DEFAULT NULL,
  `timeout` int(11) DEFAULT NULL,
  `jar_name` varchar(256) DEFAULT NULL,
  `jar_version` varchar(20) DEFAULT NULL,
  `creater_name` varchar(25) DEFAULT NULL,
  `modifier_name` varchar(25) DEFAULT NULL,
  `transfer` varchar(10) DEFAULT 'http',
  `Designed_Error_Code` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`api_id`),
  KEY `ix_artifact_Id` (`artifact_Id`),
  KEY `ix_api_group` (`api_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `mobileapi_api_group` (
  `group_id` varchar(255) NOT NULL,
  `group_name` varchar(128) NOT NULL,
  `begin_code` bigint(20) DEFAULT NULL,
  `end_code` bigint(20) DEFAULT NULL,
  `creater_name` varchar(25) DEFAULT NULL,
  `modifier_name` varchar(25) DEFAULT NULL,
  `jar_name` varchar(256) DEFAULT NULL,
  `artifact_Id` varchar(100) NOT NULL,
  `ver` varchar(20) NOT NULL,
  PRIMARY KEY (`group_id`,`group_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `mobileapi_api_param` (
  `api_id` varchar(255) NOT NULL,
  `param_order` int(11) NOT NULL,
  `param_name` varchar(255) DEFAULT NULL,
  `param_type` varchar(255) NOT NULL,
  `time_created` datetime DEFAULT NULL,
  `time_modified` datetime DEFAULT NULL,
  `is_auto` int(11) DEFAULT NULL,
  `is_RsaEncrypted` int(11) DEFAULT NULL,
  `is_AesEncrypted` int(11) DEFAULT NULL,
  `is_Required` int(11) DEFAULT NULL,
  `default_value` varchar(50) DEFAULT NULL,
  `jar_name` varchar(256) DEFAULT NULL,
  `artifact_Id` varchar(100) NOT NULL,
  `ver` varchar(20) NOT NULL,
  `param_Type_Detail` varchar(6000) DEFAULT NULL,
  PRIMARY KEY (`api_id`,`param_order`),
  KEY `ix_artifact_Id` (`artifact_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `mobileapi_error_code` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `group_name` varchar(255) DEFAULT NULL,
  `type_name` varchar(255) DEFAULT NULL,
  `artifact_Id` varchar(255) DEFAULT NULL,
  `ver` varchar(20) DEFAULT NULL,
  `jar_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=774651 DEFAULT CHARSET=utf8;